var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+\u9ed8\u8ba4\u60c5\u666f", {
    "+\u9ed8\u8ba4\u60c5\u666f": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)docker\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)sentry\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)feedly\.com$/.test(host)) return "+proxy";
        if (/^raw\.githubusercontent\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)steamstatic\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)t\.me$/.test(host)) return "+proxy";
        if (/(?:^|\.)githubassets\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)vimeo\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)funcaptcha\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)github\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)pixiv\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)dropbox\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)dropboxusercontent\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)javdb007\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)dmm\.co\.jp$/.test(host)) return "+proxy";
        if (/(?:^|\.)redd\.it$/.test(host)) return "+proxy";
        if (/(?:^|\.)reddit\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)enthusiastgaming\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)mega\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)mega\.co\.nz$/.test(host)) return "+proxy";
        if (/(?:^|\.)squarespace-cdn\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)googlesyndication\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)ytimg\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)discord\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)discordapp\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)discordapp\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)mega\.nz$/.test(host)) return "+proxy";
        if (/(?:^|\.)gstatic\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)googleusercontent\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)nvidia\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)discord\.gg$/.test(host)) return "+proxy";
        if (/(?:^|\.)googlevideo\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)execute-api\.us-east-1\.amazonaws\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)cardinalcommerce\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)braintreegateway\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)patreonusercontent\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)patreon\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)nyaa\.fun$/.test(host)) return "+proxy";
        if (/(?:^|\.)nyaa\.pro$/.test(host)) return "+proxy";
        if (/(?:^|\.)jav\.guru$/.test(host)) return "+proxy";
        if (/(?:^|\.)javdb004\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)javlibrary\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)redditmedia\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)redditstatic\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)wikimedia\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)twimg\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)ipfs\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)dlsite\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)ajax\.googleapis\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)dropboxstatic\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)google\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)tdesktop\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)telegram\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)libgen\.rs$/.test(host)) return "+proxy";
        if (/(?:^|\.)9hentai\.to$/.test(host)) return "+proxy";
        if (/(?:^|\.)nhentai\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)imhentai\.xxx$/.test(host)) return "+proxy";
        if (/(?:^|\.)e-hentai\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)nhentai\.xxx$/.test(host)) return "+proxy";
        if (/(?:^|\.)sakura-cat\.club$/.test(host)) return "+proxy";
        if (/(?:^|\.)openai\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)pinimg\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)imgur\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)youtube-nocookie\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)tumblr\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)loverslab\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)v2ex\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)pximg\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)jnn-pa\.googleapis\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)ggpht\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)fontawesome\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)ip111\.cn$/.test(host)) return "+proxy";
        if (/(?:^|\.)steamcommunity\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)steampowered\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)twitter\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)tweetdeck\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)twitpic\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)pscp\.tv$/.test(host)) return "+proxy";
        if (/(?:^|\.)youtube\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)onedrive\.live\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)wikipedia\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)githubusercontent\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)git\.io$/.test(host)) return "+proxy";
        if (/(?:^|\.)simplyhentai\.org$/.test(host)) return "+proxy";
        if (/(?:^|\.)nhentai\.net$/.test(host)) return "+proxy";
        if (/(?:^|\.)singlelogin\.me$/.test(host)) return "+proxy";
        if (/(?:^|\.)pdfdrive\.com$/.test(host)) return "+proxy";
        if (/^sstm\.moe$/.test(host)) return "+proxy";
        if (/^terawell\.net$/.test(host)) return "+proxy";
        if (/^files\.nexus-cdn\.com$/.test(host)) return "+proxy";
        if (/^t\.co$/.test(host)) return "+proxy";
        if (/(?:^|\.)nexusmods\.com$/.test(host)) return "+proxy";
        if (/(?:^|\.)v2fly\.org$/.test(host)) return "+proxy";
        return "+__ruleListOf_\u9ed8\u8ba4\u60c5\u666f";
    },
    "+__ruleListOf_\u9ed8\u8ba4\u60c5\u666f": "DIRECT",
    "+proxy": function(url, host, scheme) {
        "use strict";
        if (host === "127.0.0.1" || host === "::1" || host.indexOf(".") < 0 || /^localhost$/.test(host) || /^192\.168\.0\./.test(host)) return "DIRECT";
        return "SOCKS5 127.0.0.1:10808; SOCKS 127.0.0.1:10808";
    }
});